import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "../app/_component/navbar/Navbar";
import Footer from "./_component/footer/Footer";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { FaTruck } from "react-icons/fa";
import { FaArrowRotateLeft, FaShieldHalved } from "react-icons/fa6";
import { BiSupport } from "react-icons/bi";
import SessionProviderWrapper from "./_component/sessionProviderWrapper/SessionProviderWrapper";
import CartContextProvider from "./_context/CartContext";
import { getCartItems } from "@/api/services/route.services";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{

  const cartItems = await getCartItems()
  return (
    <html lang="en">
      <body
        className={`${exo.variable} font-exo  antialiased`}
        suppressHydrationWarning={true}
      >
        <CartContextProvider cartItems={cartItems}>
          <SessionProviderWrapper>
            <SidebarProvider defaultOpen={false}>
              <div className="flex flex-col w-full ">
                <Navbar></Navbar>
                <Toaster />
                <main className="w-full">{children}</main>
                <section className="border-y border-main-color-subtle bg-[#F0FDF4]">
                  <div className="container mx-auto px-4 py-6 ">
                    <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
                      <div className="flex gap-3 items-center">
                        <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-main-color-subtle text-main-color">
                          <FaTruck size={22} />
                        </div>
                        <div>
                          <h3 className=" text-[#101828] font-semibold text-[14px] leading-5">
                            Free Shipping
                          </h3>
                          <p className="text-text-color leading-4 text-[12px] font-medium">
                            On orders over 500 EGP
                          </p>
                        </div>
                      </div>
                      <div className="flex gap-3 items-center">
                        <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-main-color-subtle text-main-color">
                          <FaArrowRotateLeft size={22} />
                        </div>
                        <div>
                          <h3 className=" text-[#101828] font-semibold text-[14px] leading-5">
                            Easy Returns
                          </h3>
                          <p className="text-text-color leading-4 text-[12px] font-medium">
                            14-day return policy
                          </p>
                        </div>
                      </div>
                      <div className="flex gap-3 items-center">
                        <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-main-color-subtle text-main-color">
                          <FaShieldHalved size={22} />
                        </div>
                        <div>
                          <h3 className=" text-[#101828] font-semibold text-[14px] leading-5">
                            Secure Payment
                          </h3>
                          <p className="text-text-color leading-4 text-[12px] font-medium">
                            100% secure checkout
                          </p>
                        </div>
                      </div>
                      <div className="flex gap-3 items-center">
                        <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-main-color-subtle text-main-color">
                          <BiSupport size={22} />
                        </div>
                        <div>
                          <h3 className=" text-[#101828] font-semibold text-[14px] leading-5">
                            24/7 Support
                          </h3>
                          <p className="text-text-color leading-4 text-[12px] font-medium">
                            Contact us anytime
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <Footer />
              </div>
            </SidebarProvider>
          </SessionProviderWrapper>
        </CartContextProvider>
      </body>
    </html>
  );
}
